// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD56zbHmeSvg-KZro2rZwL0JlwJ6pz5a_4',
    appId: '1:483285088195:web:56ba9cdae399032f106f76',
    messagingSenderId: '483285088195',
    projectId: 'zefaaf-16c8a',
    authDomain: 'zefaaf-16c8a.firebaseapp.com',
    storageBucket: 'zefaaf-16c8a.appspot.com',
    measurementId: 'G-FMGG4Q4QER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzZmbXXjNrk8NuwhZbrArYvlnBuQRarqM',
    appId: '1:483285088195:android:f6b5ee8766ac11a0106f76',
    messagingSenderId: '483285088195',
    projectId: 'zefaaf-16c8a',
    storageBucket: 'zefaaf-16c8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRreDkb-jIHsSS4W7YblURzJuUE9UCQCA',
    appId: '1:483285088195:ios:0be885db241dcfab106f76',
    messagingSenderId: '483285088195',
    projectId: 'zefaaf-16c8a',
    storageBucket: 'zefaaf-16c8a.appspot.com',
    androidClientId:
        '483285088195-1p0v4f6n7qh9alafacjenbrchrhee9jn.apps.googleusercontent.com',
    iosClientId:
        '483285088195-q62499fu7j50r1tam9ogms00vs1hd8p0.apps.googleusercontent.com',
    iosBundleId: 'com.dreamsoft.zefaaf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRreDkb-jIHsSS4W7YblURzJuUE9UCQCA',
    appId: '1:483285088195:ios:b463dbb86c0626aa106f76',
    messagingSenderId: '483285088195',
    projectId: 'zefaaf-16c8a',
    storageBucket: 'zefaaf-16c8a.appspot.com',
    androidClientId:
        '483285088195-1p0v4f6n7qh9alafacjenbrchrhee9jn.apps.googleusercontent.com',
    iosClientId:
        '483285088195-3jgeek9kqifq738fb72b317pc9np3qbl.apps.googleusercontent.com',
    iosBundleId: 'com.dreamsoft.mobile',
  );
}
