import 'package:get/get.dart';

class LanguageTranslation extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar_EG': {
          'Other Lang': 'English',
          'Tab1 Title': 'الشاشه الاولي',
          'الرئيسيه': 'الرئيسيه',
          'ourMessage': 'رسالتنا',
          'messages': 'رسائل',
          'fontSizeHint': 'أختر حجم الخط',
          'all': 'الكل',
          'requestImage': 'طلب عرض الصورة',
          'agents': 'وكلاء زفاف',
          'add_agents': 'إنضم لوكلائنا',
          'upgradeToUpload': 'قم بترقية حسابك للفضية لرفع صورتك',
          'marrageOnSunna': 'الزواج في ضوء السُنة',
          'privacy': 'سياسة الخصوصية',
          'howToUse': 'ڤيديو تعريفي',
          '"couldn`tPay"': 'لم نستطع الاشتراك فى الباقة الان',
          'watchMyAccount': 'شاهد حسابي',
          'takeCareOfMe': 'اهتم بى',
          'veilLevel': 'الحجاب',
          'searchError': 'لم نستطع أكمال البحث',
          'TypeNameFirst': 'أدخل اسم اولا',
          'choiceFilter': 'إختر الفلتر الذي تحتاجه',
          'photoRequest': 'طلب عرض الصورة',
          'notification': 'الإشعارات',
          'personalData': 'البيانات الشخصية',
          'CollageAndWork': 'الدراسة والعمل',
          'aboutMe': 'عن نفسي',
          'intro': 'مستوى الدخل الشهري',
          'job': 'الوظيفة',
          'age': 'العمر',
          'yes': 'نعم',
          'no': 'لا',
          'SelectedNatonality': 'اختيار الجنسية',
          'email': 'ايميل',
          'SelectedHome': 'مكان الاقامة',
          'name': 'الاسم',
          'ignore': 'تجاهل',
          'chat': 'محادثة',
          'addToInterest': 'اضف لقائمة الإعجاب',
          'complain': 'شكوى',
          'MarriageType': 'نوع الزواج',
          'weight': 'الوزن',
          'socialStatus': 'الحالة الاجتماعية',
          'length': 'الطول',
          'more': 'المزيد',
          'SkinColor': 'لون البشرة',
          'bodyBuilding': 'بنية الجسم',
          'medicalStatus': 'الحالة الصحية',
          'physicalDes': 'المواصفات الجسدية',
          'smoke': 'التدخين',
          'religiousLevel': 'مستوى التدين',
          'PrayLevel': 'الصلاة',
          'bearStatus': 'حالة اللحية',
          'religious': 'الإلتزام الديني',
          'field': 'مجال العمل',
          'recentUsers': 'أحدث المشتركين',
          'finance': 'الوضع المادي',
          'Collage': 'المؤهل التعليمي',
          'changePassword': 'تغيير كلمة المرور',
          'changeNumber': 'تغيير رقم الموبايل',
          'topicsForRead': 'مواضيع جديدة',
          'admiredMe': 'أبدوا اعجابهم',
          'watchedMyAccount': 'شاهد حسابى',
          'bear': 'اللحية',
          'changeStatus': 'تغيير حالتك',
          'upgrade': 'الترقية الآن',
          'favorites': 'قائمة الإعجاب',
          'ignore': 'قائمة التجاهل',
          'nationality': 'الدولة',
          'nationalityHint': 'أختر الدولة',
          'bearHint': 'أختر اللحية',
          'country': 'الجنسية',
          'marriageType': 'نوع الزواج',
          'marriageTypeHint': 'أختر نوع الزواج',
          'place': 'مكان الاقامة',
          'fontSize': 'حجم الخط',
          'ageSelect': 'العمر',
          'theArticles': 'المقالات',
          'acceptAndSwear': 'موافق وأقسم على ماسبق',
          'makeNewAccount': 'أنشاء حساب جديد',
          'notifications': 'الإشعارات',
          'Height': 'الطول',
          'allowedToMessageMe': 'المسموح لهم بمراسلتي',
          'settings': 'الإعدادات',
          'search': 'بحث',
          'placeHint': 'أختر مكان الاقامة',
          'socialStatusHint': 'أختر الحالة الإجتماعية',
          'countryHint': 'أختر الدولة',
          'evaluateApp': 'قيم التطبيق',
          'packages': 'الباقات',
          'successStories': 'قصص نجاح',
          'interestList': 'قائمة الإعجاب',
          'neglectList': 'قائمة التجاهل',
          'send': 'إرسال',
          'content': 'المحتوى',
          'address': 'العنوان',
          'messageType': 'نوع الرسالة',
          'messageTypeHint': 'أدخل نوع الرسالة',
          'callUS': 'إتصل بنا',
          'nightMode': 'الوضع الليلي',
          'married': 'متزوج',
          'single': 'أعزب',
          'subscribers': 'المشتركين',
          'articles': 'مقالات',
          'details': 'التفاصيل',
          'logOut': 'تسجيل الخروج',
          'sharingApp': 'مشاركة التطبيق',
          'contactUs': 'استمارة زفاف',
          'Tab2 Title': 'الشاشه الثانيه',
          'Tab3 Title': 'الشاشه الثالثه',
          'Tab 1 Page': 'محتوي الصفحة الاولي',
          'Change Theme': 'تغيير الثيم'
        }
      };
}
